name: CompatHelper
on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
          ssh_password: ${{ secrets.DOCUMENTER_PASSPHRASE }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
